controller_list:
  - name: fake_rob1_controller
    type: $(arg fake_execution_type)
    joints:
      - rob1_joint_1
      - rob1_joint_2
      - rob1_joint_3
      - rob1_joint_4
      - rob1_joint_5
      - rob1_joint_6
  - name: fake_rob2_controller
    type: $(arg fake_execution_type)
    joints:
      - rob2_joint_1
      - rob2_joint_2
      - rob2_joint_3
      - rob2_joint_4
      - rob2_joint_5
      - rob2_joint_6
  - name: fake_rob1_track_controller
    type: $(arg fake_execution_type)
    joints:
      - rob1_linear_axis_joint
      - rob1_joint_1
      - rob1_joint_2
      - rob1_joint_3
      - rob1_joint_4
      - rob1_joint_5
      - rob1_joint_6
  - name: fake_rob2_track_controller
    type: $(arg fake_execution_type)
    joints:
      - rob2_linear_axis_joint
      - rob2_joint_1
      - rob2_joint_2
      - rob2_joint_3
      - rob2_joint_4
      - rob2_joint_5
      - rob2_joint_6
initial:  # Define initial robot poses per group
  - group: rob1_track
    pose: home1
  - group: rob2_track
    pose: home2