version: '2'
services:
  moveit-service:
    image: gramaziokohler/ros-noetic-moveit
    container_name: moveit-service
    environment:
      - ROS_HOSTNAME=moveit-service
      - ROS_MASTER_URI=http://ros-core:11311
      # GUI: To forward the GUI to an external X11 server (eg. VcXsrv), uncomment the following line
      - DISPLAY=host.docker.internal:0.0 # tell ROS to send the video image outside of the container
    depends_on:
      - ros-core
    volumes:
      - ../../abb_experimental:/root/catkin_ws/src/abb_experimental
      - ./abb_irbt6004_670_support:/root/catkin_ws/src/abb_irbt6004_670_support #track
      - ./abb_irbt6004_670_moveit_config:/root/catkin_ws/src/abb_irbt6004_670_moveit_config
    command:
      - roslaunch
      - --wait
      - abb_irbt6004_670_moveit_config
      - demo.launch
      # To launch the RVIZ GUI, change the following to true
      - use_rviz:=false
      - pipeline:=ompl

  # # to create configuration uncomment the following lines
  # # also run the XLaunch server on windows
  # moveit-service-setup-assistant:
  #   image: gramaziokohler/ros-noetic-moveit
  #   container_name: moveit-service-setup-assistant
  #   environment:
  #     - ROS_HOSTNAME=moveit-service-setup-assistant
  #     - ROS_MASTER_URI=http://ros-core:11311
  #     # GUI: To forward the GUI to an external X11 server (eg. XMing), uncomment the following line
  #     - DISPLAY=host.docker.internal:0.0
  #   depends_on:
  #     - ros-core
  #   volumes:
  #     - ../../abb_experimental:/root/catkin_ws/src/abb_experimental
  #     - ./abb_irbt6004_670_support:/root/catkin_ws/src/abb_irbt6004_670_support
  #     - ./abb_irbt6004_670_moveit_config:/root/catkin_ws/src/abb_irbt6004_670_moveit_config
  #   command:
  #     - roslaunch
  #     - --wait
  #     - moveit_setup_assistant
  #     - setup_assistant.launch

  ros-core:
    image: gramaziokohler/ros-noetic-moveit
    container_name: ros-core
    ports:
      - "11311:11311"
    command:
      - roscore

  ros-bridge:
    image: gramaziokohler/ros-noetic-moveit
    container_name: ros-bridge
    environment:
      - "ROS_HOSTNAME=ros-bridge"
      - "ROS_MASTER_URI=http://ros-core:11311"
    ports:
      - "9090:9090"
    depends_on:
      - ros-core
    command:
      - roslaunch
      - --wait
      - rosbridge_server
      - rosbridge_websocket.launch

  ros-fileserver:
    image: gramaziokohler/ros-noetic-moveit
    container_name: ros-fileserver
    environment:
      - ROS_HOSTNAME=ros-fileserver
      - ROS_MASTER_URI=http://ros-core:11311
    depends_on:
      - ros-core
    volumes:
      - ../../abb_experimental:/root/catkin_ws/src/abb_experimental
      - ./abb_irbt6004_670_support:/root/catkin_ws/src/abb_irbt6004_670_support # track
      - ./abb_irbt6004_670_moveit_config:/root/catkin_ws/src/abb_irbt6004_670_moveit_config
    command:
      - roslaunch
      - --wait
      - file_server
      - file_server.launch
